<a href="https://colab.research.google.com/github/Madhaveffai/pytorch-learning/blob/main/week1/Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basic MathOps

In [1]:
import torch

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print(a + b)
print(a * b)
print(a ** 2)
print(torch.sqrt(a))

A = torch.rand(3,4)
B = torch.rand(4,2)
print(A@B)
print(A.shape, B.shape)

tensor([5., 7., 9.])
tensor([ 4., 10., 18.])
tensor([1., 4., 9.])
tensor([1.0000, 1.4142, 1.7321])
tensor([[1.7652, 1.6655],
        [1.4038, 1.3888],
        [1.6917, 1.7922]])
torch.Size([3, 4]) torch.Size([4, 2])


Broadcasting

In [2]:
x = torch.ones(3,4)
v = torch.tensor([1.0, 2.0, 3.0, 4.0])

print(x + v)

tensor([[2., 3., 4., 5.],
        [2., 3., 4., 5.],
        [2., 3., 4., 5.]])


In-place vs out-of-place

In [3]:
x = torch.tensor([1.0, 2.0, 3.0])

y = x + 1
x.add_(1)

print(x)

tensor([2., 3., 4.])


Reductions

In [4]:
x = torch.rand(3,4)

print(x.sum())
print(x.sum(dim=0)) #sum along rows
print(x.sum(dim=1)) #sum along cols
print(x.mean())
print(x.max())
print(x.argmax())

tensor(6.3901)
tensor([1.9910, 1.5672, 1.8536, 0.9784])
tensor([1.9605, 2.8229, 1.6067])
tensor(0.5325)
tensor(0.9909)
tensor(4)


Create two random tensors of shape (4, 3) and (3, 5). Matrix multiply them. Then sum the result along dim=0 and print the shape.

In [7]:
a = torch.rand(4,3)
b = torch.rand(3,5)

y = a@b

print(y.sum(dim=0))
print(y.sum(dim=0).shape)

tensor([3.0939, 1.0949, 2.1841, 2.8071, 4.8874])
torch.Size([5])
