<a href="https://colab.research.google.com/github/Madhaveffai/pytorch-learning/blob/main/week1/Tensor_101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Tensors

In [2]:
import torch

a = torch.tensor([1.0, 2.0, 3.0])
b = torch.zeros(3,4)
c = torch.ones(2,3)
d = torch.rand(3,3)

print(a.shape)
print(b.shape)
print(d.dtype)

torch.Size([3])
torch.Size([3, 4])
torch.float32


Reshaping and Indexing

In [3]:
x = torch.arange(12, dtype=torch.float32) #[0,1,2,3,4....11]
x_2d = x.reshape(3,4) #3 rows and 4 cols
x_2d_T = x_2d.T #transpose

print(x_2d)
print(x_2d[0]) # first row
print(x_2d[:, 1]) # second column
print( x_2d[1, 2])

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([0., 1., 2., 3.])
tensor([1., 5., 9.])
tensor(6.)


CPU vs GPU

In [4]:
print(torch.cuda.is_available())

x_cpu = torch.rand(3,3)
x_gpu = x_cpu.to("cuda") #move to GPU
x_back = x_gpu.to("cpu") #move back

print(x_gpu.device)

True
cuda:0
